name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Defina o branch que você quer usar para deploy (ex: main)

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftph_server }}
        username: ${{ secrets.ftph_user }}
        password: ${{ secrets.ftph_password }}
